#! /usr/bin/env python
import sferes

def build(bld):
    osg = not bld.all_envs['default']['NO_OSG']
    #libs = 'EIGEN2 ROBDYN BOOST ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR '
    libs = 'EIGEN3 ROBDYN  BOOST BOOST_TIMER ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR ROS BAYESIAN_OPTIMIZATION BOOST_CHRONO RT'
    cxxflags = bld.get_env()['CXXFLAGS']
    if osg:
        libs += ' OSG'

    model = bld.new_task_gen('cxx', 'staticlib')
    model.source = 'hexapod.cc '
    model.includes = '. ../../ /usr/include /usr/local/include'
    model.target = 'hexapod'
    model.uselib = libs



    sferes.create_variants(bld,
                           source = 'hexa_supg_hyperneat.cpp',
                           uselib_local = 'sferes2 hexapod',# robot',
                           uselib = libs,
                           target = 'hexa_supg_hyperneat',
                           json = '',
                           variants = ['ANGLED_30 ORIENTFB TEXT',    'ANGLED_30 ORIENTFB GRAPHIC', \
                                   'ANGLED_60 ORIENTFB TEXT',        'ANGLED_60 ORIENTFB GRAPHIC', \
                            'OFBV30 ANGLED_30 ORIENTFB TEXT', 'OFBV30 ANGLED_30 ORIENTFB GRAPHIC', \
                            'OFBV30 ANGLED_60 ORIENTFB TEXT', 'OFBV30 ANGLED_60 ORIENTFB GRAPHIC', \
                            'OFBV45 ANGLED_30 ORIENTFB TEXT', 'OFBV45 ANGLED_30 ORIENTFB GRAPHIC', \
                            'OFBV45 ANGLED_60 ORIENTFB TEXT', 'OFBV45 ANGLED_60 ORIENTFB GRAPHIC'])
