#! /usr/bin/env python
import sferes

def build(bld):
    osg = not bld.all_envs['default']['NO_OSG']
    #libs = 'EIGEN2 ROBDYN BOOST ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR '
    libs = 'EIGEN3 ROBDYN  BOOST BOOST_TIMER ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR ROS BAYESIAN_OPTIMIZATION BOOST_CHRONO RT'
    cxxflags = bld.get_env()['CXXFLAGS']
    if osg:
        libs += ' OSG'

    model = bld.new_task_gen('cxx', 'staticlib')
    model.source = 'hexapod.cc '
    model.includes = '. ../../ /usr/include /usr/local/include'
    model.target = 'hexapod'
    model.uselib = libs



    sferes.create_variants(bld,
                           source = 'hexa_supg_hyperneat.cpp',
                           uselib_local = 'sferes2 hexapod',# robot',
                           uselib = libs,
                           target = 'hexa_supg_hyperneat',
                           json = '',
                           variants = ['ORIENTFB ANGLED_60 RANDOM TEXT', \
                                       'OFBV18 ORIENTFB ANGLED_60 RANDOM TEXT', \
                                       'OFBV36 ORIENTFB ANGLED_60 RANDOM TEXT'])#, 'OFBV36 ORIENTFB ANGLED_30 GRAPHIC'])#, \
                           # 'OFBV36 ORIENTFB LONG BIAS_30N GRAPHIC', 'OFBV36 ORIENTFB LONG BIAS_30N GRAPHIC', \
                           # 'ORIENTFB LONG BIAS_30N GRAPHIC', 'ORIENTFB LONG BIAS_30N GRAPHIC'])
                           #  'OFBV90 ORIENTFB BIAS_60 GRAPHIC', 'OFBV90 ORIENTFB BIAS_60 GRAPHIC', \
                           #  'OFBV70 ORIENTFB BIAS_60 GRAPHIC', 'OFBV70 ORIENTFB BIAS_60 GRAPHIC', \
                           #  'OFBV50 ORIENTFB BIAS_60 GRAPHIC', 'OFBV50 ORIENTFB BIAS_60 GRAPHIC', \
                           #  'OFBV36 ORIENTFB BIAS_60 GRAPHIC', 'OFBV36 ORIENTFB BIAS_60 GRAPHIC', \
                           #  'OFBV24 ORIENTFB BIAS_60 GRAPHIC', 'OFBV24 ORIENTFB BIAS_60 GRAPHIC', \
                           #  'OFBV18 ORIENTFB BIAS_60 GRAPHIC', 'OFBV18 ORIENTFB BIAS_60 GRAPHIC', \
                           #  'OFBV10 ORIENTFB BIAS_60 GRAPHIC', 'OFBV10 ORIENTFB BIAS_60 GRAPHIC'])
                           # 'LONG BIAS_30N GRAPHIC', 'LONG BIAS_30N GRAPHIC', \
